# TODO: pre-release - may need to add a service for running local models, and/or local database volume

services:
  cli:
    build:
      context: .
      args:
        INSTALL_DEV: "true" # include dev tools if your CLI needs them
    command: [ "python", "scripts/run_cli.py" ]
    environment:
      - ENV=dev
  # api:
  #   build:
  #     context: .
  #     args:
  #       INSTALL_DEV: "false" # runtime deps only
  #   command: [ "python", "-m", "myapp.api" ] # e.g., uvicorn myapp.api:app --host 0.0.0.0 --port 8000
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ENV=prod
