### DEFAULT CLI THEME ###
# The CLI can be configured to use different colors and formatting for the prompts and messages for each script generate-ws, fillout-ws, etc

theme:
  # pre defined color options: black, red, green, yellow, blue, magenta, cyan, white, bright_black, bright_red, bright_green, bright_yellow, bright_blue, bright_magenta, bright_cyan, bright_white, or #hex
  # formatting options: bold, dim, italic, underline, blink, blink2, reverse, conceal, strike, underline2, frame, encircle, overline
  intro: "bold blue"
  outtro: "bold blue"
  # Special user messages with type="info"
  info: "bold bright_black"
  # The input prompt for user
  input: "bold cyan" 
  error: "bold red"
  user-prompt: "bold cyan"
  simulation-response: "bold green"